### ISSUE TITLE
deneme ;)

### ISSUE THREAD

**Issue by LuNiZz** [LuNiZz/davet#1]
YnUgdGFiaWtpIGlzaW4gc2FrYSBraXNtaSwgY29rIGtvbGF5IHNlbmluIGljaW4gYnVudSB5YXBtYWsuCnNveWxlIGJpciBldHJhZnRhIGRvbGFuIGJha2FsaW0sIGJ1cmFsYXJkYSBiaXIgeWVyZGUgYmlyIGRhdmV0IGxpbmtpIHZhci4ga29sYXkgZ2Vsc2luIDsp

**Comment by karanruzgar** [comment]
: )

**Comment by platongoktug** [comment]
bu tabiki isin saka kismi, cok kolay senin icin bunu yapmak.
soyle bir etrafta dolan bakalim, buralarda bir yerde bir davet linki var. kolay gelsin ;)

Not for easy but never give up

**Comment by pectonic** [comment]
> YnUgdGFiaWtpIGlzaW4gc2FrYSBraXNtaSwgY29rIGtvbGF5IHNlbmluIGljaW4gYnVudSB5YXBtYWsuCnNveWxlIGJpciBldHJhZnRhIGRvbGFuIGJha2FsaW0sIGJ1cmFsYXJkYSBiaXIgeWVyZGUgYmlyIGRhdmV0IGxpbmtpIHZhci4ga29sYXkgZ2Vsc2luIDsp

c2EgYWJpLCB0b2ZhxZ8gdmFyIG3EsT8g8J+koCA=

**Comment by ulvi75** [comment]
siktir git ya dolandırıcı ananı sikiyim


Can Ahmet Aydın ***@***.***>, 2 Ara 2021 Per, 14:11 tarihinde
şunu yazdı:

**Comment by pectonic** [comment]
> 

dWxhbiBkb2xhbmTEsXLEsWPEsWtsxLFrbGEgbmUgYWxha2FzxLEgdmFyCgpodHRwczovL3d3dy55b3V0dWJlLmNvbS93YXRjaD92PTRUeC00aTdJdWhB
