### ISSUE TITLE
Davet mi, haa?

### ISSUE THREAD

**Issue by borfirbora** [LuNiZz/davet#1]
# Merhaba Sevgili **Can YAVUZ** Abi

_Discord_ davet kodunu buldum fakat **kesinlikle** davet geçersiz diyor, haberin olsun.

**Comment by cankatx** [comment]
Evet bende kodu buldum fakat davet geçersiz diyor.

**Comment by alikaptan09** [comment]
Geçersiz Davet :(

**Comment by ssgregss** [comment]
davet kodu çalışıyor iyi bakmamızsınız :)

**Comment by hatipoglukadir** [comment]
Bendede çalışmadı

**Comment by ODAKAB** [comment]
Tüm bulduklarınızı kullanın başta ben de kodu değiştirdiler diye öyle olduğunu sandım

**Comment by cankatx** [comment]
Çalışıyor sadece ilk bulduğunuz değil ;)

**Comment by Xannex2** [comment]
bulamadım bir ipucu verebilecek var mı ? Garibanın yüzü gülür mü...

**Comment by graciasbr** [comment]
bende bir önceki kodu çözmüştüm fakat o zamana göre 4 saat önce can abinin yeni bir bulmaca koyduğunu farkettim ve bunu çözemiyorum. Kod yerine girsemde yanlış, hash analyzer da yanıt bulamadım, codechefteki tüm yöntemleri denedim, acaba neyi yanlış yapıyorum.

**Comment by cankatx** [comment]
discord.gg/Em7a2ag7SE ben haksız yere yasaklandım buyrun sokabildiğiniz kadar insanları sokun

**Comment by serdaresenturk** [comment]
Bulduğumuz şeye muhtemelen bir şey yapacağız ama, acaba ne? 🥲
