### ISSUE TITLE
QmVsa2kgeWFyZMSxbWPEsSBvbHVy

### ISSUE THREAD

**Issue by QyaniX** [LuNiZz/davet#11]
QWxwaGFiZXQgLSAxMw==

**Comment by QyaniX** [comment]
QWxwaGFiZXQgLSAxMyBMZXR0ZXJz

**Comment by Blacknewt** [comment]
eWFwYWNhxJ/EsW4gxZ9ha2FuxLFuIGFtaw==

**Comment by RuinedMeyus** [comment]
UmljayByb2xsZWQgYmVrbGVyZGltIA==

**Comment by QyaniX** [comment]
Umlja3JvbGwgZGFoYSDDtm5jZSB5YXDEsWxtxLHFnyDDtnpnw7xuIG9sbWFsxLEgOkQ=

**Comment by RuinedMeyus** [comment]
bWFudMSxa2zEsQ==
