### ISSUE TITLE
1.5 sene olmadı kardeşim nereye gitti sunucu yaa

### ISSUE THREAD

**Issue by ISYHACK** [LuNiZz/davet#2]
ben birşey anlamadım sunucu durduk yere kayboldu bu arada aradığım şey sanırsam bu değil https://discord.com/invite/Rz........

**Comment by Xannex2** [comment]
arkadaşlar ufak bir ipucu verebilir misiniz

**Comment by discover02** [comment]
aHR0cHM6Ly93d3cueW91dHViZS5jb20vd2F0Y2g/dj1kUXc0dzlXZ1hjUQo=

**Comment by Themirx** [comment]
bende denedim ama davet geçersiz diyor
