### ISSUE TITLE
QnVsZHVndW0gaGVyIHNleSBidXJhZGEgYmFzYXJpbGFyIHlpZ2lkaW0u

### ISSUE THREAD

**Issue by Afkborn** [LuNiZz/davet#8]
link: uggcf://qvfpbeq.pbz/srngherf = https://discord.com/features

66 = B
0x41 = A
97 = a
chr(66), chr(0x41), chr(0xDD), chr(0xF62), 0xA42, 0xB24, 0x00, 0x421, 0o214, 0o5362, chr(97)
(66, 65, 221, 3938, 2626, 2852, 0, 1057, 140, 2802, 97)
BAÝརੂତС૲a

doSvAC
	HEpsiz
	mjXRXu
	GcsdHD
	fTjatl
	mLaFgt
	lYJJWb
	lwafmf
	ZtBzul
	AzpmfO

slave  
	SBNXue
	WPhjrH
	TvIAXT
	jltiij	
	SUYodX
	cgNEKM
	jCncWC
	JkcbmP
	Wceogi
	OHNlXt
	lRDYyF
	SBvoSS
	fJBnNN
	OHNlXt
	lRDYyF
	SBvoSS
	fJBnNN
	mjXRXu
	lwafmf

**Comment by atesanilerdem** [comment]
Bunlar invite kodu değil arkadaşlar. K.g. :)

**Comment by Vixen061** [comment]
bende bunların hepsine ulaştım ama bir yere varamıyorum
